### PR TITLE
Add table of contents, extract examples.md, rationale.md, and alternatives.md

### PR DESCRIPTION
**Pull request by bitjson**
@joshmg and @thesquaregroot here's a branch that splits out those non-critical sections. I think this is a bit more approachable – what do you think?

### CODE REVIEW

**Comment by bitjson** [comment]
Preview: https://github.com/bitjson/cashtokens/blob/4e4123b772cd78c1a0a4cbb04e4d3df950aeb8c3/readme.md

**Comment by bitjson** [comment]
@thesquaregroot good point, thanks! Ya, the subsection links aren't terribly helpful in the top-level TOC – feels way more approachable with only the primary sections linked.

I also trimmed out some stray headings from the auto-generated list in the `Technical Specification` subsections. Feels much better moving that down into it's own section, thanks!

New preview: https://github.com/bitjson/cashtokens/blob/910c93f3261d394afb06f5eca0601423b033a22b/readme.md

**Comment by thesquaregroot** [comment]
Yeah, nice.  Looks good!

**Comment by bitjson** [comment]
Merged 🚀

Thanks!

**Pull request merged**
